[build]
  publish = "dist"
  command = "npm run build"

# Disable Netlify drawer / collaborative preview widget
[context.production.environment]
  NETLIFY_DRAWER = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
